packages:
  - apps/*
  - packages/*

catalog:
  '@types/jest': ^30.0.0
  '@types/node': ^22.18.10
  '@typescript-eslint/eslint-plugin': ^8.46.1
  '@typescript-eslint/parser': ^8.46.1
  eslint: ^9.37.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  jest: ^30.2.0
  prettier: ^3.6.2
  ts-jest: ^29.4.5
  ts-loader: ^9.5.4
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  typescript: ^5.9.3

ignoredBuiltDependencies:
  - bcrypt